# Generated by Django 3.1.4 on 2021-01-02 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template1', models.BooleanField(default=True)),
                ('template2', models.BooleanField(default=False)),
                ('cvColor', models.BooleanField(default='rgb(29, 202, 130)')),
                ('fullName', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('zip_code', models.IntegerField()),
                ('cvEmail', models.EmailField(max_length=254)),
                ('phoneNum', models.IntegerField()),
                ('objective', models.TextField()),
                ('hobbyandinterest', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobTitle', models.CharField(max_length=255)),
                ('companyName', models.CharField(max_length=255)),
                ('employmentDateStart', models.CharField(max_length=50)),
                ('employmentDateEnd', models.CharField(max_length=50)),
                ('cvinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.cvinfo')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalAccomplishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('praccomplishment1', models.CharField(max_length=500)),
                ('praccomplishment2', models.CharField(max_length=500)),
                ('praccomplishment3', models.CharField(max_length=500)),
                ('praccomplishment4', models.CharField(max_length=500)),
                ('praccomplishment5', models.CharField(max_length=500)),
                ('cvinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.cvinfo')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalAccomplishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paccomplishment1', models.CharField(max_length=500)),
                ('paccomplishment2', models.CharField(max_length=500)),
                ('paccomplishment3', models.CharField(max_length=500)),
                ('paccomplishment4', models.CharField(max_length=500)),
                ('paccomplishment5', models.CharField(max_length=500)),
                ('cvinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.cvinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolandcollege', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('grade', models.IntegerField()),
                ('date', models.IntegerField()),
                ('cvinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.cvinfo')),
            ],
        ),
    ]
