# Generated by Django 3.1.4 on 2021-01-04 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210102_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvinfo',
            name='cvColor',
            field=models.CharField(default='rgb(29, 202, 130)', max_length=255),
        ),
    ]
