# Generated by Django 3.1.4 on 2021-01-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20210104_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvinfo',
            name='cvEmail',
            field=models.EmailField(max_length=254),
        ),
    ]
