# Generated by Django 3.1.4 on 2021-01-06 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20210106_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolandcollege', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('grade', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('date', models.IntegerField(blank=True, null=True)),
                ('cvinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.cvinfo')),
            ],
        ),
    ]
