# Generated by Django 3.1.4 on 2021-01-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_education1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education1',
            name='date',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
