# Generated by Django 3.1.4 on 2021-01-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20210106_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='education1',
            name='date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
