# Generated by Django 3.1.4 on 2021-01-07 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20210106_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolandcollege', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('grade', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.CharField(blank=True, max_length=255, null=True)),
                ('cvinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.cvinfo')),
            ],
        ),
    ]
