# Generated by Django 3.1.4 on 2021-01-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_auto_20210119_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvimg',
            name='img',
            field=models.FileField(default=1, upload_to='media'),
            preserve_default=False,
        ),
    ]
