# Generated by Django 3.1.4 on 2021-01-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_auto_20210119_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvimg',
            name='img',
            field=models.FileField(blank=True, default='settings.MEDIA_ROOT/logos/avatar.png', null=True, upload_to='media'),
        ),
    ]
